import jwt from 'jsonwebtoken'

// Return the token generated by jwt.verify().

const generateToken = (userId) => {
  const token = jwt.sign(
    { userId }, // token identification
    'KDOWKODWOKDKO', // secret phrase
    { expiresIn: "7 days" } // options
  )

  return token
}

export default generateToken
