import jwt from 'jsonwebtoken'

// Return the token generated by jwt.verify().

const generateToken = (userId) => {
  const token = jwt.sign(
    { userId },
    'KDOWKODWOKDKO',
    { expiresIn: "7 days" }
  )

  return token
}

export default generateToken
